### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by Halleck45** [Halleck45/ast-metrics#1]
AST Metrics aims to become a leading, language-agnostic, user-friendly, and educational code analyzer.

This is my first project in Go, and I'm completely new to the language. Contributions are highly welcome, particularly to enhance stability and performance.

**The v1 roadmap is as follows:**

**Supported Languages**

- [x] PHP (full)
- [x] Golang (partial)
- [x] TypeScript
- [ ] Java
- [x] Python (partial)
- [ ] Dart

**Features**

- [x] Unified AST descriptor via Protobuf
- [x] CLI report
- [x] Support for non-interactive environments (CI)
- [x] Configuration file support (.ast-metrics.yaml)
- [x] HTML report
- [x] Git analysis
- [x] Markdown report
- [x] Easy integration with Github, via Github actions
- [x] Easy integration with Gitlab CI, via Templates

**Metrics**

- [x] Halstead metric
- [x] Bug probability
- [x] FanIn / FanOut (afferent / efferent coupling)
- [x] Cyclomatic complexity
- [x] Maintainability index
- [x] Size (lines of code, comments, logical lines)
- [x] Bus factor
- [x] Commits, top committers
- [x] Risked files

All of this is subject to change, and discussions may lead to new ideas or modifications to the roadmap.

> **v2 will probably include**: 'failIf' conditions, relations between objects, OpenAI plugin...

Thank you in advance for your assistance!

**Comment by DeGraciaMathieu** [comment]
Hello @Halleck45 

Would it be possible to add a search option on certain pages? I'm specifically thinking about the "risk" page.

Often, after initiating an analysis of a project, I need to focus on specific components of my application (commands, controllers, a set of specific classes within a namespace, etc ...).

Currently, this requires me to rerun the entire analysis just to target these classes.

Thank you !

**Comment by Halleck45** [comment]
Hi @DeGraciaMathieu , thanks for the suggestion!

To avoid having to restart the tool, [I just added a `--watch` option](https://github.com/Halleck45/ast-metrics/pull/27) that refreshes the page and the HTML report as soon as a file is updated.

Regarding the search functionality, what do you think? Should we add a `--filter` argument? Or maybe a search field that appears in the window when you press `Ctrl + F?`

Could you please [create a discussion here](https://github.com/Halleck45/ast-metrics/discussions/new/choose) ?

**Comment by KorDum** [comment]
Hi!
Unfortunately, I found that there is no Distance from the main sequence metric. Are you planning to add it?

**Comment by alanpoulain** [comment]
I opened an [issue](https://github.com/phpmetrics/PhpMetrics/issues/511) in PhpMetrics, but I think it could be done in this project instead, WDYT of supporting the [OpenMetrics specification](https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md)?

It could be then be used for instance in [GitLab](https://docs.gitlab.com/ee/ci/testing/metrics_reports.html) to have the metrics directly in the MR!

It seems there are some available packages in Go as well, for instance: https://github.com/bsm/openmetrics

**Comment by Halleck45** [comment]
@alanpoulain excellent idea !

I hope https://github.com/Halleck45/ast-metrics/pull/70 will help you

**Comment by alanpoulain** [comment]
Wow already! :rocket: Nice to see it implemented, thank you! Now I need to replace PhpMetrics with AST Metrics :smile:

**Comment by alanpoulain** [comment]
How to you plan to support the newer versions of PHP if VKCOM/php-parser is not updated anymore?
